### ISSUE TITLE
登录，服务器无响应

### ISSUE THREAD

**Issue by xyfDoYourLove** [zjwshisb/laravel-vue-admin#2]
按照安装步骤启动项目后，报服务器无响应，BASE_API应该怎么修改才能解决呢

**Comment by zjwshisb** [comment]
如果你没修改项目名称的话应该是不用修改的，确认你本地服务已经开启，http://localhost/laravel-vue-admin/public/index.php在浏览器访问有相应

**Comment by xyfDoYourLove** [comment]
> 如果你没修改项目名称的话应该是不用修改的，确认你本地服务已经开启，[http://localhost/laravel-vue-admin/public/index.php在浏览器访问有相应](http://localhost/laravel-vue-admin/public/index.php%E5%9C%A8%E6%B5%8F%E8%A7%88%E5%99%A8%E8%AE%BF%E9%97%AE%E6%9C%89%E7%9B%B8%E5%BA%94)

项目名称没有变，http://localhost/laravel-vue-admin/public/index.php浏览器里访问没反应，我本地的环境是wampServer，我通过php artisan serve启动了laravel，试了试也不行，是我少了什么东西吗

**Comment by zjwshisb** [comment]
应该是你的wamp服务有问题，ngnix启动了静态html文件能访问的话可能就是路由配置的问题，先要确保laravel能访问到
