### ISSUE TITLE
permission的中间件有错

### ISSUE THREAD

**Issue by yangzming** [zjwshisb/laravel-vue-admin#3]
`public function handle($request, Closure $next)
    {
        $user = $request->user();
        $permission  = Route::currentRouteName();
        if ($user->is_super || in_array($permission, $this->except) || $user->hasPermissionTo($permission)) {
            return $next($request);
        }
        throw new ForbiddenException();
    }`
这里面的$user->hasPermissionTo($permission) 会报 Spatie\Permission\Exceptions\PermissionDoesNotExist 
请问是怎么回事

**Comment by zjwshisb** [comment]
应该是你的当前路由名称在permission表里不存在



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 子命 <notifications@github.com&gt;
发送时间: 2020年4月17日 14:22
收件人: zjwshisb/laravel-vue-admin <laravel-vue-admin@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[zjwshisb/laravel-vue-admin] permission的中间件有错 (#3)
